jfinder-project/authentication/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("forgotten-password-reset-modal/", PasswordResetModal.as_view(), name="pw_reset_modal"),
    path('forgotten-password-reset/', ResetForgottenPasswordView.as_view(), name="forgotten_password_reset"),
    path('forgotten-password-reset/<str:uuidb64>/<str:token>', ResetForgottenPasswordView.as_view(), name="forgotten_password_reset_confirmation"),
    path("delete-account-modal/", AccountDeleteModalView.as_view(), name="delete_account_modal"),
    path('change-email/', ChangeEmailView.as_view(), name="change_email"),
    path('change-email/<str:uuidb64>/<str:token>', ChangeEmailView.as_view(), name="change_email_activation"),
    path('change-password/', ChangePasswordView.as_view(), name="change_password"),
]

jfinder-project/jfinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('schema-viewer/', include('schema_viewer.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('jobs/', include('jobs.urls')),
    path('cvbuilder/', include('cvbuilder.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jfinder-project/jobs/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('search/', SearchView.as_view(), name = "search"),
    path('job-details/<str:offer_id>', JobDetailsView.as_view(), name="job_details"),
    path('job-details-full', JobDetailsFullView.as_view(), name="job_details_full"),
    path('job-report/<str:offer_id>', ReportOfferModal.as_view(), name="job_report"),
    path('job-bookmark/<int:offer_id>', BookamrkOfferView.as_view(), name="job_bookmark"),
    path("job-apply/<int:id>", ApplicationCreateModal.as_view(), name="job_apply"),
    path('job-apply/internal-file-modal', ApplicationWithInternalFileModal.as_view(), name="application_internal_file_modal"),
    path('job-apply/external-file-modal', ApplicationWithExternalFileModal.as_view(), name="application_external_file_modal"),
]

jfinder-project/authentication/models.py
from django.db import models
from django import forms
from django.utils import timezone
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager

# Create your models here.


class UserManager(BaseUserManager):

    def _create_user(self, email: str, password: str, **extrafields):
        if not email:
            raise ValueError("You have not provided the email address.")

        email = self.normalize_email(email)
        user = self.model(email=email, **extrafields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, password, **extrafields):
        extrafields.setdefault("is_staff", False)
        extrafields.setdefault('is_superuser', False)

        return self._create_user(email=email, password=password, **extrafields)

    def create_superuser(self, email=None, password=None, **extrafields):
        extrafields.setdefault("is_staff", True)
        extrafields.setdefault('is_superuser', True)

        return self._create_user(email=email, password=password, **extrafields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(blank=True, default="", unique=True)
    name = models.CharField(max_length=255, default="", blank=True)

    is_active = models.BooleanField(default=False)
    is_email_confirmed = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_organization = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_logged_in = models.DateTimeField(blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta():
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.name or self.email.split("@")[0]


class UserEmailChangeRequestModel(models.Model):

    request_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('authentication.User', on_delete=models.CASCADE, blank=False)
    new_email = models.EmailField(blank=False)
    validation_token = models.TextField()


class UserForgottenPasswordResetRequestModel(models.Model):

    request_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('authentication.User', on_delete=models.CASCADE, blank=False)
    validation_token = models.TextField()

jfinder-project/authentication/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate
from django import forms

from django.forms import Form, ValidationError

from .models import User


class CustomAuthenticationForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'autofocus': True}))
    password = forms.CharField(
        max_length=63, widget=forms.PasswordInput(attrs={'autofocus': True}))

    def clean(self):
        super(CustomAuthenticationForm, self).clean()
        email = self.cleaned_data.get('email')
        if email:
            self.user_cache = authenticate(
                username=email,
                password=self.cleaned_data.get('password')
            )
            if self.user_cache is None:
                raise forms.ValidationError(
                    'Invalid email or password'
                )
        return self.cleaned_data


class CustomRegistrationForm(forms.ModelForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'autofocus': True}), required=True)
    name = forms.CharField(
        max_length=63, widget=forms.TextInput(), required=True)
    password = forms.CharField(
        max_length=63, widget=forms.PasswordInput(attrs={'autofocus': True}), required=True)
    password_confirm = forms.CharField(
        max_length=63, widget=forms.PasswordInput(attrs={'autofocus': True}), required=True)
    is_organization = forms.BooleanField(
        required=False, initial=False, widget=forms.CheckboxInput())

    class Meta:
        model = User
        fields = (
            "name",
            "email",
            "is_organization",
            "password",
        )

    def clean(self):
        super(CustomRegistrationForm, self).clean()
        email = self.cleaned_data.get('email')
        if self.cleaned_data.get("password") != self.cleaned_data.get("password_confirm"):
            raise forms.ValidationError("Passwords do not match")
        return self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        print("user in save ", user)
        user.set_password(self.cleaned_data.get('password'))
        user.save()
        print('user after save and after commit and after pwd set ',
              user, user.password)
        return user


class PasswordChangeForm(Form):

    current_password = forms.CharField(max_length=30, min_length=8, required=True, widget=forms.PasswordInput(attrs= {'autofocus': True}))
    new_password = forms.CharField(max_length=30, min_length=8, required=True, widget=forms.PasswordInput(attrs= {'autofocus': True}))
    new_password_confirm = forms.CharField(max_length=30, min_length=8, required=True, widget=forms.PasswordInput(attrs= {'autofocus': True}))

    def __init__(self, user: User, data = None):
        self.user = user
        super(PasswordChangeForm, self).__init__(data)

    def clean_current_password(self):
        password = self.cleaned_data["current_password"]
        if not self.user.check_password(password):
            print("invalid password")
            raise ValidationError("Invalid password")
        print("Password ok")
    
    def clean(self):
        super().clean()
        if self.cleaned_data.get('new_password') != self.cleaned_data.get("new_password_confirm"):
            print("Unmatchingpasswords")
            raise forms.ValidationError("New Password and Confirmed New Password must be the same")
        print("Password matching")
        return self.cleaned_data
    

class EmailChangeForm(Form):

    password = forms.CharField(max_length=30, min_length=8, required=True, widget=forms.PasswordInput(attrs={}))
    new_email = forms.EmailField(max_length=30, min_length=8, required=True, widget=forms.EmailInput(attrs={}))

    def __init__(self, user: User, data = None):
        self.user = user
        super(EmailChangeForm, self).__init__(data)

    def clean_current_password(self):
        password = self.cleaned_data["password"]
        if not self.user.check_password(password):
            raise ValidationError("Invalid Password")
        

class ForgottenPasswordEmailForm(Form):

    email = forms.EmailField(max_length=30, min_length=5, required = True, widget = forms.EmailInput(attrs={'autofocus': True}))


class ForgottenPasswordResetForm(Form):

    new_password = forms.CharField(min_length=8, max_length=30, required=True, widget=forms.PasswordInput(attrs= {}))
    new_password_confirm = forms.CharField(max_length=30, min_length=8, required=True, widget=forms.PasswordInput(attrs= {}))

    def clean(self):
        super().clean()
        if self.cleaned_data.get('new_password') != self.cleaned_data.get("new_password_confirm"):
            raise forms.ValidationError("New Password and Confirmed New Password must be the same")
        return self.cleaned_data

jfinder-project/templates/authentication/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load django_htmx %}
{% load widget_tweaks %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static "css/output.css" %}" rel="stylesheet">
    <script src="https://unpkg.com/hyperscript.org@0.9.14"></script>
    {% htmx_script %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body class="grid min-h-[100dvh] w-full grid-rows-[auto_1fr_auto] bg-white overflow-x-hidden">
    <header class="">

        {% block header %}
        {% endblock header %}

    </header> 

    {% block content%}
    {% endblock content%}
        
    <footer class="w-full h-14 grid grid-cols-4 place-items-center link-text bg-white border-t-primary border-t-2">
        <p>Terms and conditions</p>
        <p>FAQ</p>
        <p>Need help?</p>
        <p>Legal basis</p>
    </footer>
</body>
</html>

jfinder-project/templates/authentication/forgot_password_modal.html
{% load static %}

{% load widget_tweaks %}

<div class="grid grid-cols-1 place-items-center fixed top-0 bottom-0 right-0 left-0 z-[100]" id="modal" _="on closeModal remove me">
    <div class="absolute top-0 bottom-0 right-0 left-0 bg-gray-950/60 -z-1" _="on click trigger closeModal">
    </div>
        <div class="w-3/5 max-w-[500px] bg-white rounded-2xl grid grid-cols-1 place-items-center gap-5 py-10 px-20">
            <div class="w-full">
                <p class="font-primary text-black text-2xl">Forgot your password?</p>
                <p class="font-secondary text-black text-sm">We will send a password reset link to your email</p>
            </div>

            <form id="password-reset-link-request" hx-post="{% url "pw_reset_modal" %}" hx-target="#messages" hx-swap="innerHTML">

                {% csrf_token %}

                {% render_field form.email class="form-input-field text-sm" placeholder="Your email goes here"%}
                
            </form>

            <div id="messages" class="">

            </div>
            {% comment %} <div class="w-full font-secondary text-[16px]">
                <p>Email</p>
                <input class="form-input-field" type="email" placeholder="Your email goes here">
            </div> {% endcomment %}
            <div class="w-full">
                <button type="submit" 
                form="password-reset-link-request" 
                class="w-full h-7 bg-primary font-secondary border-primary border-2 text-sm text-white text-center rounded-2xl shadow-md transition-all duration-400 hover:scale-102 hover:ease-in-out"
                >Send the link for password reset</button>
            </div>
            <div _="on click trigger closeModal" class="w-full">
                <input _="on click trigger closeModal" class="w-full h-7 bg-white font-secondary text-sm text-black text-center rounded-2xl shadow-md border-gray-400 border-2 transition-all duration-400 hover:scale-102 hover:ease-in-out" type="button" value="Go back to Log In" _="on click trigger closeModal">
            </div>
            <div class="w-full flex flex-row justify-center font-secondary text-black text-sm">
                <p>Don't have account yet? <a class="link-text" href="{% url "register" %}">Register here </a></p>
            </div>
        </div>
</div>

jfinder-project/templates/authentication/login.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Login Page{% endblock title %}

{% block header %}
{% endblock header %}

{% block content %}

<main class="w-full min-h-[calc(100dvh-56px)] grid place-items-center grid-cols-1">
    {% comment %} <div class="w-10/12 h-full grid grid-cols-1 place-items-center px-10 py-20">
        <div class="w-1/2 h-[200px] bg-primary rounded-2xl">

        </div>
        <div class="w-full grid grid-cols-1 place-items-center gap-5">
            <p class="font-primary text-primary text-5xl w-full text-center">JFinder</p>
            <p class="font-primary text-2xl text-black text-center">Finding a job - made easy!</p>
        </div>
    </div>
    <form class="form-display px-10 py-20" method="post" action={% url "login" %}>
        {% csrf_token %}
        {{ message }}
        <div class="w-full">
            <p class="font-primary text-black text-2xl">Hello!</p>
            <p class="font-secondary text-black text-sm">Enter your login data to enter the website</p>
        </div>
        <div class="w-full  font-secondary text-black text-[16px]">
            <p>Email</p>
            {% render_field form.email type="email" id="id_email" placeholder="Your email goes here" class="form-input-field" %}
        </div>
        <div class="w-full font-secondary text-black text-[16px]">
            <p>Password</p>
            {% render_field form.password type="password" id="id_password" placeholder="Your password goes here" class="form-input-field" %}
        </div>
        <div class="w-full  flex flex-row justify-between font-secondary text-black text-sm">
            <p>Don't have account yet? <a class="link-text" href="{% url "register" %}">Register here.</a></p>
            <p hx-get="{% url "pw_reset_modal" %}" hx-target="body" hx-swap="beforeend" class="link-text cursor-pointer"> Forgot password?</p>
        </div>
        <div class='w-full '>
            <input class="w-full h-7 bg-primary font-secondary border-primary border-2 text-sm text-white text-center rounded-2xl shadow-md transition-all duration-400 hover:scale-102 hover:ease-in-out" type="submit" value="Log in!">
        </div>
        <div class="w-full  grid grid-cols-3 place-items-center">
            <div class="w-full h-[1px] border-t-[1px] border-black"></div>
            <p class="text-black font-secondary text-sm">or</p>
            <div class="w-full h-[1px] border-t-[1px] border-black"></div>
        </div>
        <div class="w-full ">
            <input class="w-full h-7 bg-white font-secondary text-sm text-black text-center rounded-2xl shadow-md border-gray-400 border-2 transition-all duration-400 hover:scale-102 hover:ease-in-out" type="button" value="Log in with Google">
        </div>
    </form> {% endcomment %}

    <div class="w-full max-w-4xl grid grid-cols-1 md:grid-cols-2 bg-white rounded-xl shadow-lg overflow-hidden">

        <!-- Left side (branding) -->
        <div class="hidden md:flex flex-col items-center justify-center bg-blue-50 p-8">
            <div class="w-40 h-40 bg-blue-400 rounded-lg mb-6"></div>
            <h1 class="text-2xl font-bold text-blue-600">JFinder</h1>
            <p class="text-gray-600 mt-2">Finding a job – made easy!</p>
        </div>

        <!-- Right side (form) -->
        <div class="p-8 flex flex-col justify-center">
            <h2 class="text-2xl font-bold text-gray-800 mb-2">Welcome back 👋</h2>
            <p class="text-sm text-gray-500 mb-6">Enter your login details to continue</p>

            <form class="space-y-4" hx-post="{% url "login" %}" hx-swap="none">
                {% csrf_token %}
                <!-- Email -->
                <div>
                    {% comment %} <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                    <input id="email" type="email" placeholder="you@example.com"
                        class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"> {% endcomment %}
                    <label for="id_email" class="text-sm font-medium text-gray-700">Email</label>
                    {% render_field form.email type="email" placeholder="you@example.com" class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" %}
                </div>

                <!-- Password -->
                <div>
                    {% comment %} <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
                    <input id="password" type="password" placeholder="********"
                        class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"> {% endcomment %}
                        <label for="id_password" class="text-sm font-medium text-gray-700">Passowrd</label>
                        {% render_field form.password type="password" placeholder="********" class="w-full mt-1 px-4 py-2 rounded-md border border-slate-300 focus:ring-2 focus:ring-blue-500 focus:outline-none" %}
                </div>

                <!-- Actions -->
                <div class="flex items-center justify-between text-sm">
                    <a href="{% url "register" %}" class="text-blue-600 hover:underline">Register here</a>
                    <p class="text-blue-600 hover:underline cursor-pointer" hx-target="body" hx-swap="beforeend" hx-get="{% url 'pw_reset_modal' %}">Forgotten password?</p>
                </div>

                <!-- Login Button -->
                <button type="submit"
                class="w-full bg-blue-600 text-white py-2 rounded-md font-medium hover:bg-blue-700 transition">Log In</button>

                <!-- Divider -->
                <div class="flex items-center gap-2 my-4">
                    <hr class="flex-1 border-gray-300">
                    <span class="text-sm text-gray-500">or</span>
                    <hr class="flex-1 border-gray-300">
                </div>

                <!-- Google Login -->
                <button type="button"
                    class="w-full border border-gray-300 py-2 rounded-md flex items-center justify-center gap-2 hover:bg-gray-50 transition">
                    <img src="https://www.svgrepo.com/show/475656/google-color.svg" alt="Google" class="w-5 h-5">
                    Log in with Google
                </button>
            </form>
        </div>
    </div>
</main>


{% endblock content %}

jfinder-project/templates/authentication/reg_tmp.html
<!DOCTYPE html>
<html lang="en">
<head> 
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Register - JFinder</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class=" bg-gray-100 grid grid-rows-[1fr_auto] grid-cols-1 place-items-center min-h-screen overflow-x-clip">

  <!-- Login Card -->
  <div class="w-full max-w-2xl grid grid-cols-1 bg-white rounded-xl shadow-lg overflow-hidden">

    <!-- Right side (form) -->
    <div class="p-8 flex flex-col justify-center">
      <h2 class="text-2xl font-bold text-gray-800 mb-2">Welcome back 👋</h2>
      <p class="text-sm text-gray-500 mb-6">Enter your login details to continue</p>

      <form class="space-y-4">
        <!-- Email -->
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700">Name</label>
          <input id="email" type="email" placeholder="Name Surname"
            class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>

        <div>
          <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
          <input id="email" type="email" placeholder="you@example.com"
            class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>

        <!-- Password -->
        <div>
          <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
          <input id="password" type="password" placeholder="********"
            class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>

        <div>
          <label for="password" class="block text-sm font-medium text-gray-700">Confirm Password</label>
          <input id="password" type="password" placeholder="********"
            class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>

        <!-- Actions -->
        <div class="flex items-center justify-left text-sm">
          <a href="#" class="text-blue-600 hover:underline">Already have an account</a>
        </div>

        <!-- Login Button -->
        <button type="submit"
          class="w-full bg-blue-600 text-white py-2 rounded-md font-medium hover:bg-blue-700 transition">Sign Up</button>

        <!-- Divider -->
        <div class="flex items-center gap-2 my-4">
          <hr class="flex-1 border-gray-300">
          <span class="text-sm text-gray-500">or</span>
          <hr class="flex-1 border-gray-300">
        </div>

        <!-- Google Login -->
        <button type="button"
          class="w-full border border-gray-300 py-2 rounded-md flex items-center justify-center gap-2 hover:bg-gray-50 transition">
          <img src="https://www.svgrepo.com/show/475656/google-color.svg" alt="Google" class="w-5 h-5">
          Log in with Google
        </button>
      </form>
    </div>
  </div>

  <!-- Footer -->
  <footer class="w-full h-10 mt-[1rem] flex justify-center gap-6 text-sm text-gray-500">
    <a href="#" class="hover:text-blue-600">Terms</a>
    <a href="#" class="hover:text-blue-600">FAQ</a>
    <a href="#" class="hover:text-blue-600">Help</a>
    <a href="#" class="hover:text-blue-600">Legal</a>
  </footer>

</body>
</html>

jfinder-project/templates/authentication/register.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Registration{% endblock title %}

{% block header %}
{% endblock header %}

{% block content %}


<main class="w-full min-h-[calc(100dvh-56px)] grid grid-cols-1 place-items-center">
    <div class="w-full max-w-2xl grid grid-cols-1 bg-white rounded-xl shadow-lg overflow-hidden">

        <!-- Right side (form) -->
        <div class="p-8 flex flex-col justify-center">
            <h2 class="text-2xl font-bold text-gray-800 mb-1">Welcome back 👋</h2>
            <p class="text-sm text-gray-500 mb-6">Enter your login details to continue</p>

            <form class="space-y-4" hx-post="{% url 'register' %}" hx-swap="none">
            <!-- Email -->
            <div>
                <label for="id_name" class="block text-sm font-medium text-gray-700 mb-1">Name</label>
                {% comment %} <input id="email" type="email" placeholder="Name Surname"
                class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"> {% endcomment %}
                {% render_field form.name placeholder="Name" type="text" class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" %}
            </div>

            <div>
                <label for="id_email" class="block text-sm font-medium text-gray-700 mb-1">Email</label>
                {% comment %} <input id="email" type="email" placeholder="you@example.com"
                class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"> {% endcomment %}
                {% render_field form.email placeholder="you@gmail.com" type="text" class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" %}
            </div>

            <!-- Password -->
            <div>
                <label for="id_password" class="block text-sm font-medium text-gray-700">Password</label>
                {% comment %} <input id="password" type="password" placeholder="********"
                class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"> {% endcomment %}
                {% render_field form.password placeholder="*******" type="password" class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none "%}
            </div>

            <div>
                <label for="id_password_confirm" class="block text-sm font-medium text-gray-700">Confirm Password</label>
                {% comment %} <input id="password" type="password" placeholder="********"
                class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"> {% endcomment %}
                {% render_field form.password_confirm placeholder="*******" type="password" class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none "%}
            </div>

            <!-- Actions -->
            <div class="flex items-center justify-left text-sm">
                <a href="{% url 'login' %}" class="text-blue-600 hover:underline">Already have an account</a>
            </div>

            <!-- Login Button -->
            <button type="submit"
                class="w-full bg-blue-600 text-white py-2 rounded-md font-medium hover:bg-blue-700 transition">Sign Up</button>

            <!-- Divider -->
            <div class="flex items-center gap-2 my-4">
                <hr class="flex-1 border-gray-300">
                <span class="text-sm text-gray-500">or</span>
                <hr class="flex-1 border-gray-300">
            </div>

            <!-- Google Login -->
            <button type="button"
                class="w-full border border-gray-300 py-2 rounded-md flex items-center justify-center gap-2 hover:bg-gray-50 transition">
                <img src="https://www.svgrepo.com/show/475656/google-color.svg" alt="Google" class="w-5 h-5">
                Log in with Google
            </button>
            </form>
        </div>
    </div>
</main>


{% comment %} 
<section class="w-full h-full grid grid-cols-1 place-items-center place-content-center gap-2">
    <div class="h-10">
        <p class="font-primary text-primary text-3xl">JFinder</p>
    </div>
    <form method="post" class="form-display gap-2 max-w-[600px] pt-5 pb-5 px-10  border-primary rounded-2xl">
        {% csrf_token %}
        <div class="w-full">
            <p class="text-left font-primary text-2xl">Register you personal account</p>
            <p class="text-left font-secondary text-sm">Fill out the registration form</p>
        </div>
        <div class="w-full font-secondary flex flex-row gap-2">
            {% render_field form.is_organization type="checkbox" id="id_is_organization" class="" %}
            <p>Are you a company?</p>
        </div>
        <div class="w-full font-secondary">
            <p>Name</p>
            {% render_field form.name type="text" id="id_name" placeholder="Your name goes here" class="form-input-field"%}
        </div>
        <div class="w-full font-secondary">
            <p>Email</p>
            {% render_field form.email type="email" id="id_email" placeholder="Your email goes here" class="form-input-field"%}
        </div>
        <div class="w-full font-secondary">
            <p>Password</p>
            {% render_field form.password type="password" id="id_password" placeholder="Your password goes here" class="form-input-field" %}
        </div>
        <div class="w-full font-secondary">
            <p>Repeat Password</p>
            {% render_field form.password_confirm type="password" id="id_password_confirm" placeholder="Repeat your password" class="form-input-field" %}
        </div>
        <div class="w-full">
            <input class="form-btn-primary font-secondary text-[16px]" type="submit" name="" id="" value="Sign up!">
        </div>
        <div class="w-full  grid grid-cols-3 place-items-center">
            <div class="w-full h-[1px] border-t-[1px] border-balck"></div>
            <p class="text-black font-secondary text-sm">or</p>
            <div class="w-full h-[1px] border-t-[1px] border-balck"></div>
        </div>
        <div class="w-full ">
            <input class="w-full h-7 bg-white font-secondary text-sm text-black text-center rounded-2xl shadow-md border-gray-400 border-2 transition-all duration-400 hover:scale-102 hover:ease-in-out" type="button" value="Log in with Google">
        </div>
    </form>
</section> {% endcomment %}
{% endblock content %}