jfinder-project/dashboard/urls.py
from django.urls import path, include
from dashboard.views import *

urlpatterns = [
    path("<str:selected>", DashbaordBaseView.as_view(), name="dashboard"),
    path("", DashbaordBaseView.as_view(), name="dashboard"),
    path("navigation/stats/", StatsView.as_view(), name="stats"),
    path("navigation/inbox/", InboxView.as_view(), name="inbox"),
    path("navigation/bookmarkes/", BookmarkedListView.as_view(), name="bookmarks"),
    path("navigation/settings/", SettingsView.as_view(), name="settings"),
    path("navigation/trend-plot/", TrendPlotView.as_view(), name = "trend_plot"),
]

jfinder-project/jfinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('schema-viewer/', include('schema_viewer.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('jobs/', include('jobs.urls')),
    path('cvbuilder/', include('cvbuilder.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jfinder-project/jobs/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('search/', SearchView.as_view(), name = "search"),
    path('job-details/<str:offer_id>', JobDetailsView.as_view(), name="job_details"),
    path('job-details-full', JobDetailsFullView.as_view(), name="job_details_full"),
    path('job-report/<str:offer_id>', ReportOfferModal.as_view(), name="job_report"),
    path('job-bookmark/<int:offer_id>', BookamrkOfferView.as_view(), name="job_bookmark"),
    path("job-apply/<int:id>", ApplicationCreateModal.as_view(), name="job_apply"),
    path('job-apply/internal-file-modal', ApplicationWithInternalFileModal.as_view(), name="application_internal_file_modal"),
    path('job-apply/external-file-modal', ApplicationWithExternalFileModal.as_view(), name="application_external_file_modal"),
]

jfinder-project/main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('documents/<int:index>', DocumentView.as_view(), name="get_document"),
    path('education/create', EducationCreateView.as_view(), name = 'education_create'),
    path('education/update/<int:pk>', EducationUpdateView.as_view(), name = 'education_update'),
    path('education/delete/<int:pk>', EducationDeleteView.as_view(), name = 'education_delete'),
    path('experience/create', ExperienceCreateView.as_view(), name = 'experience_create'),
    path('experience/update/<int:pk>', ExperienceUpdateView.as_view(), name = 'experience_update'),
    path('experience/delete/<int:pk>', ExperienceDeleteView.as_view(), name = 'experience_delete'),
]

jfinder-project/main/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
import uuid

# Create your models here.

from jobs.models import CountriesChoices

PERSONAL_LINK_CHOICES = {
    'IN': "Instagram",
    'FB': "Facebook",
    'TT': "TickTock",
    'X': "X",
    'PW': "Personal Website",
}

DEGREE_CHOICES = {
    'BS': "Bachelor",
    'MA': "Masters",
    'PhD': "Doctor of Philosophy",
}

class FileSourceTypeChoices(models.TextChoices):
    EXTERNAL = 'EX', _("External")
    INTERNAL = 'IN', _("Internal")


def upload_profile_path(instance, filename):
    ext = filename.split('.')[-1]
    return 'profile_img/{0}.{1}'.format(uuid.uuid4(), ext)


def upload_document_path(instance, filename):
    ext = filename.split('.')[-1]
    return 'document/{0}.{1}'.format(str(uuid.uuid4()) + filename.split('.')[-2], ext)


class UserProfile(models.Model):

    user = models.OneToOneField(
        'authentication.User', on_delete=models.CASCADE)

    biography = models.TextField(max_length=1000, null=True, blank=True)
    profile_img = models.ImageField(
        upload_to=upload_profile_path, blank=True, null=True)
    skills = models.ManyToManyField('jobs.Skill', related_name="skills")
    accepting_offers = models.BooleanField(default=True)
    contact_info_phone = models.TextField(max_length=20, blank=True)
    address = models.TextField(max_length = 100, blank=True, default="Not specified")
    country_of_residence = models.TextField(choices = CountriesChoices.choices, blank = True, default="Not Specified")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'id'], name='unique_user_profile'
            )
        ]

    def __str__(self):
        return str(self.id)


class CompanyProfile(models.Model):

    user = models.OneToOneField(
        'authentication.User', on_delete=models.CASCADE)

    moto = models.TextField(max_length=100, blank=True, default="")
    employee_num = models.PositiveIntegerField()
    headquarters_address = models.TextField(
        max_length=100, blank=True, null=False)
    profile_img = models.ImageField(
        upload_to=upload_profile_path, blank=True, null=True)
    about_us = models.TextField(max_length=1000)

    def __str__(self):
        return str(self.id)


class Document(models.Model):
    name = models.TextField(max_length=50, null=False,
                            blank=False, default="New File")
    uploader = models.ForeignKey(
        'authentication.User', on_delete=models.CASCADE)
    file = models.FileField(upload_to=upload_document_path)

    source_type = models.TextField(max_length = 2, choices=FileSourceTypeChoices.choices, null=False, default=FileSourceTypeChoices.EXTERNAL)

    def __str__(self):
        return self.name


class Settings(models.Model):

    user = models.OneToOneField(
        'authentication.User', on_delete=models.CASCADE)

    dark_theme = models.BooleanField(default=False)
    newsletter_subscribed = models.BooleanField(default=False)
    offer_change_notification = models.BooleanField(default=True)
    contact_info_show = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'settings'
        verbose_name_plural = 'settings_set'

    def __str__(self):
        return "{}'s Settings profile".format(self.id)


class PersonalLink(models.Model):

    profile = models.ForeignKey('main.UserProfile', on_delete=models.CASCADE)

    link = models.CharField(max_length=255, default="")
    media_type = models.TextField(choices=PERSONAL_LINK_CHOICES)


class Education(models.Model):

    profile = models.ForeignKey('main.UserProfile', on_delete=models.CASCADE)

    institution = models.CharField(max_length=100, null=False)
    specialization = models.CharField(max_length=100, null=False)
    start_year = models.DateField(null=False, blank=False)
    end_year = models.DateField(null=True, blank=True)
    ongoing = models.BooleanField(null=False, blank=True)
    degree = models.TextField(choices=DEGREE_CHOICES, default = 'BS')
    gpa = models.IntegerField(blank=True)
    diploma = models.ForeignKey('main.Document', on_delete=models.CASCADE, blank = True, null=True)
    comment = models.TextField(max_length=1000, blank=True)

    def __str__(self):
        return str(self.id)

    
class Experience(models.Model):

    profile = models.ForeignKey('main.UserProfile', on_delete=models.CASCADE)

    company = models.CharField(max_length=100, null=False)
    position = models.CharField(max_length=100, null=False)
    start_year = models.DateField(null=False, blank=False)
    end_year = models.DateField(null=True, blank=True)
    ongoing = models.BooleanField(null=False, blank=True)
    description = models.TextField(max_length= 1000, null=False)
    duties = models.TextField(max_length=300, null=False)

    def __str__(self):
        return str(self.id)

jfinder-project/main/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.template.loader import render_to_string
from authentication.models import User
from main.models import UserProfile, Document, Education, Experience
from main.forms import EducationForm, ExperienceForm

from jfinder.utils import MessageContext, MessageAction

# Create your views here.

class ProfileView(View):

    template_name = "main/profile.html"

    def get(self, request):
        user_profile = get_object_or_404(UserProfile, user=request.user)
        context = {
            "profile": user_profile,
        }
        return render(request, self.template_name, context = context)

class EducationCreateView(View):

    education_form = EducationForm

    education_modal = 'main/components/education_modal.html'
    education_table = 'main/components/education_table.html'
    dialog_template = 'main/components/dialog_message.html'

    def get(self, request):
        form = self.education_form()
        context = {
            'form': form,
            "action": "Create",
        }
        return render(request, self.education_modal, context=context)
    
    def post(self, request):
        user_profile = get_object_or_404(UserProfile, user=request.user)
        form = self.education_form(request.POST)
        if form.is_valid():
            print("valid form edu")
            education_instance = form.save(commit=False)
            education_instance.profile = user_profile
            education_instance.save()

            education_list = Education.objects.filter(profile = user_profile).all()
            context = {
                "education_list": education_list,
                "swap_oob": True,
            }
            html = render_to_string(self.education_table, context = context, request = request)
            response = HttpResponse(html)
            response.headers["HX-Trigger"] = '{"closeModal":true}'
            return response
        message = MessageContext(type="error", message=form.errors.as_text(), action = MessageAction(required=False))
        context = {
            "message": message.as_context()
        }
        return render(request, self.dialog_template, context=context)


class EducationUpdateView(View):

    education_form = EducationForm

    education_modal = 'main/components/education_modal.html'
    education_table = 'main/components/education_table.html'
    dialog_template = 'main/components/dialog_message.html'

    def get(self, request, pk:int):
        user_profile = get_object_or_404(UserProfile, user = request.user)
        education_entity = get_object_or_404(Education, profile = user_profile, pk = pk)
        form = self.education_form(instance=education_entity)
        context = {
            "form": form,
            "pk": pk,
            "action": "Update",
        }
        return render(request, self.education_modal, context = context)

    def post(self, request, pk:int):
        user_profile = get_object_or_404(UserProfile, user = request.user)
        education_entity = get_object_or_404(Education, profile = user_profile, pk = pk)
        form = self.education_form(request.POST, instance=education_entity)
        if form.is_valid():
            form.save()
            education_list = Education.objects.filter(profile = user_profile).all()
            context = {
                "education_list": education_list,
                "swap_oob": True,
            }
            html = render_to_string(self.education_table, context = context, request = request)
            response = HttpResponse(html)
            response.headers["HX-Trigger"] = '{"closeModal":true}'
            return response
        message = MessageContext(type="error", message=form.errors.as_text(), action = MessageAction(required=False))
        context = {
            "message": message.as_context()
        }
        return render(request, self.dialog_template, context=context)
        

class EducationDeleteView(View):

    education_form = EducationForm

    education_modal = 'main/components/education_modal.html'
    education_table = 'main/components/education_table.html'
    dialog_template = 'main/components/dialog_message.html'

    def get(self, request, pk:int):
        pass

    def post(self, request, pk:int):
        user_profile = get_object_or_404(UserProfile, user = request.user)
        education_entity = get_object_or_404(Education, profile = user_profile, pk = pk)
        education_entity.delete()
        education_list = Education.objects.filter(profile = user_profile).all()
        context = {
            "education_list": education_list,
            "swap_oob": True,
        }
        return render(request, self.education_table, context = context)
        

class ExperienceCreateView(View):

    experience_form = ExperienceForm

    experience_modal = 'main/components/experience_modal.html'
    experience_table = 'main/components/experience_table.html'
    dialog_template = 'main/components/dialog_message.html'

    def get(self, request):
        form = self.experience_form()
        context = {
            'form': form,
            "action": "Create",
        }
        return render(request, self.experience_modal, context=context)
    
    def post(self, request):
        user_profile = get_object_or_404(UserProfile, user=request.user)
        form = self.experience_form(request.POST)
        print("before form validation in exp")
        if form.is_valid():
            print("valid form exp")
            experience_instance = form.save(commit=False)
            experience_instance.profile = user_profile
            experience_instance.save()

            experience_list = Experience.objects.filter(profile = user_profile).all()
            context = {
                "experience_list": experience_list,
                "swap_oob": True,
            }
            html = render_to_string(self.experience_table, context = context, request = request)
            response = HttpResponse(html)
            response.headers["HX-Trigger"] = '{"closeModal":true}'
            return response
        print(form.errors)
        message = MessageContext(type="error", message=form.errors.as_text(), action = MessageAction(required=False))
        context = {
            "message": message.as_context()
        }
        return render(request, self.dialog_template, context=context)


class ExperienceUpdateView(View):

    experience_form = ExperienceForm

    experience_modal = 'main/components/experience_modal.html'
    experience_table = 'main/components/experience_table.html'
    dialog_template = 'main/components/dialog_message.html'

    def get(self, request, pk:int):
        user_profile = get_object_or_404(UserProfile, user = request.user)
        experience_entity = get_object_or_404(Experience, profile = user_profile, pk = pk)
        form = self.experience_form(instance=experience_entity)
        context = {
            "form": form,
            "pk": pk,
            "action": "Update",
        }
        return render(request, self.experience_modal, context = context)

    def post(self, request, pk:int):
        user_profile = get_object_or_404(UserProfile, user = request.user)
        experience_entity = get_object_or_404(Experience, profile = user_profile, pk = pk)
        form = self.experience_form(request.POST, instance=experience_entity)
        if form.is_valid():
            form.save()
            experience_list = Experience.objects.filter(profile = user_profile).all()
            context = {
                "experience_list": experience_list,
                "swap_oob": True,
            }
            html = render_to_string(self.experience_table, context = context, request = request)
            response = HttpResponse(html)
            response.headers["HX-Trigger"] = '{"closeModal":true}'
            return response
        message = MessageContext(type="error", message=form.errors.as_text(), action = MessageAction(required=False))
        context = {
            "message": message.as_context()
        }
        return render(request, self.dialog_template, context=context)
        

class ExperienceDeleteView(View):

    experience_form = ExperienceForm

    experience_modal = 'main/components/experience_modal.html'
    experience_table = 'main/components/experience_table.html'
    dialog_template = 'main/components/dialog_message.html'

    def get(self, request, pk:int):
        pass

    def post(self, request, pk:int):
        user_profile = get_object_or_404(UserProfile, user = request.user)
        experience_entity = get_object_or_404(Experience, profile = user_profile, pk = pk)
        experience_entity.delete()
        experience_list = Experience.objects.filter(profile = user_profile).all()
        context = {
            "experience_list": experience_list,
            "swap_oob": True,
        }
        return render(request, self.experience_table, context = context)


class DocumentView(View):

    def get(self, request, index:int):
        document = get_object_or_404(Document, id=index, uploader = request.user)
        # research how to supply files from backend efficiently
        pass
    

class IndexView(View):

    template_name = "main/index.html"

    def get(self, request):
        return render(request, self.template_name, context={})

jfinder-project/templates/main/index.html
{% extends "base.html" %}

{% block content %}
<div class="">
    index
</div>
{% endblock content %}

jfinder-project/templates/main/profile.html
{% load jobs_extras %}

<div class="grid grid-cols-1 md:grid-cols-[1fr_250px] gap-[1rem]">
    {% comment %} Hero card (CV also here){% endcomment %}
    <div class="flex flex-col gap-[0.5rem] items-end pr-[2rem] mb-6">
        {% include 'main/components/education_table.html' with education_list=profile.education_set.all swap_oob=False%}
        {% include 'main/components/experience_table.html' with experience_list=profile.experience_set.all swap_oob=False%}
        {% comment %} Skills {% endcomment %}
        <div id="skills" class="w-[50rem] mt-6">
            <div class="flex flex-row w-max gap-1.5 py-4 justify-center items-center text-center mb-3">
                <h2 class="text-lg font-semibold text-sky-600">Skills</h2>
                <button class="p-2 rounded-full hover:bg-sky-100">
                    ✏️
                </button>
            </div>
            <div class="flex flex-wrap w-full shrink-0 gap-[1rem] pb-[1rem]">
                {% for skill in profile.skills.all %}
                <div class="w-[auto] px-[1rem] py-[0.1rem] rounded-2xl bg-white shadow-md hover:bg-sky-100">{{skill}}</div>
                {% endfor %}
            </div>
        </div>
        {% comment %} Docs and certificates (not related to previous sections) {% endcomment %}
        <div id="docs" class="w-[50rem] mt-6">
            <h2 class="text-lg font-semibold text-sky-600 mb-3">Documents</h2>
            <div class="overflow-hidden shadow-md rounded-lg">
                <table class="table-auto border-collapse w-full">
                    <thead class="bg-blue-600">
                        <tr>
                            <td class="px-6 py-3 font-semibold text-sm text-left text-white">Name</td>
                            <td class="px-6 py-3 font-semibold text-sm text-left text-white">Last modified</td>
                            <td class="px-6 py-3 font-semibold text-sm text-left text-white">Status</td>
                            <td class="px-6 py-3 font-semibold text-sm text-left text-white">Link</td>
                            <td class="px-6 py-3 font-semibold text-sm text-left text-white">
                                <span class="block"></span>
                            </td>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200">
                        {% for _ in "111"|make_list %}
                        <tr class="hover:bg-sky-50">
                            <td><p class="px-6 py-4 text-sm text-gray-800">Documnet descriptive name with some details</p></td>
                            <td><p class="px-6 py-4 text-sm text-gray-800">24.06.2001</p></td>
                            <td>
                                <div class="flex flex-col items-center justify-center">
                                    <p class="h-8 w-max px-2 py-1 text-sm text-center text-gray-800 rounded-md border-2 border-green-600 bg-green-400/45">Saved</p>
                                </div>
                            </td>
                            <td>
                                <p class="px-6 py-4 underline text-sm text-sky-600 cursor-pointer"><a href="">Link</a></p>
                            </td>
                            <td>
                                <button class="p-2 rounded-full hover:bg-sky-100">
                                    ✏️
                                </button>
                            </td>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <aside class="hidden md:block w-56">
        <div class="sticky top-1/6 bg-white rounded-lg shadow-md p-4">
            <h3 class="text-sm font-semibold text-gray-600 mb-3">On this page</h3>
            <nav class="space-y-2">
                <a href="#education_table" 
                    class="block px-3 py-2 rounded-md text-gray-700 hover:bg-sky-50 hover:text-sky-600">
                    🎓 Education
                </a>
                <a href="#experience_table" 
                    class="block px-3 py-2 rounded-md text-gray-700 hover:bg-sky-50 hover:text-sky-600">
                    💼 Experience
                </a>
                <a href="#skills" 
                    class="block px-3 py-2 rounded-md text-gray-700 hover:bg-sky-50 hover:text-sky-600">
                    🛠️ Skills
                </a>
                <a href="#docs" 
                    class="block px-3 py-2 rounded-md text-gray-700 hover:bg-sky-50 hover:text-sky-600">
                    🚀 Documents
                </a>
            </nav>
        </div>
    </aside>
</div>